on:
  pull_request_target:
    branches: [ main ]

permissions:
  pull-requests: write

jobs:
  bench:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1", "1.10"]
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-overhaul
        with:
          julia-version: ${{ matrix.julia-version }}
          exeflags: '-O3'
